.TH "png2gds" "1" "12th July 2007" "" ""
.SH NAME
png2gds \- convert png images to gds2 layout files.

.SH SYNOPSIS
.PP
png2gds
.I png2gds input.png output.gds grid

.SH DESCRIPTION
.B png2gds
is a tool to convert png images with indexed palettes into a gds2 file. It is intended to make adding logos to chip designs much more straightforward. Each pixel will be converted to the gds2 layer according to its palette number, so a pixel with colour number 1 will become gds2 layer 1 and so on. The image is created as a single layout block called png2gds, with each pixel created as a single square in the layout, with the size of the square determined by the grid option given on the command line. It is recommended that after importing into your layout tool, all of the squares are selected and merged. This produces a much smaller layout file and also looks much better, although it has no implications for the actual layout.

.SH AUTHOR
Roger Light <roger@atchoo.org>
